create table public.notification_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email_enabled boolean not null default false,
  deadline_reminders_enabled boolean not null default false,
  critical_updates_enabled boolean not null default false,
  time_zone text not null default 'UTC' check (char_length(time_zone) between 1 and 100),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.reminders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(btrim(title)) between 1 and 120),
  target_kind text not null check (target_kind in ('article', 'checklist', 'custom')),
  target_id text check (target_id is null or target_id ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  scheduled_for timestamptz not null,
  time_zone text not null check (char_length(time_zone) between 1 and 100),
  state text not null default 'scheduled' check (state in ('scheduled', 'cancelled', 'fulfilled')),
  cancelled_at timestamptz,
  fulfilled_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint reminder_target_matches_kind check (
    (target_kind = 'custom' and target_id is null)
    or (target_kind <> 'custom' and target_id is not null)
  ),
  constraint reminder_state_matches_timestamps check (
    (state = 'scheduled' and cancelled_at is null and fulfilled_at is null)
    or (state = 'cancelled' and cancelled_at is not null and fulfilled_at is null)
    or (state = 'fulfilled' and fulfilled_at is not null and cancelled_at is null)
  )
);

create index reminders_due_lookup
on public.reminders (scheduled_for, id)
where state = 'scheduled';

create table public.notification_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('reminder-due', 'article-critical-update', 'residence-status-guidance-updated')),
  deduplication_key text not null check (char_length(deduplication_key) between 1 and 200),
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, event_type, deduplication_key)
);

alter table public.notification_preferences enable row level security;
alter table public.reminders enable row level security;
alter table public.notification_events enable row level security;

revoke all on table public.notification_preferences from anon, authenticated;
revoke all on table public.reminders from anon, authenticated;
revoke all on table public.notification_events from anon, authenticated;
grant select, insert, update, delete on table public.notification_preferences to authenticated;
grant select, insert, update, delete on table public.reminders to authenticated;
grant select on table public.notification_events to authenticated;

create policy "Users can manage their own notification preferences"
on public.notification_preferences for all to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can manage their own reminders"
on public.reminders for all to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

-- Events are generated by trusted scheduling code; account holders may only read their own events.
create policy "Users can read their own notification events"
on public.notification_events for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create trigger notification_preferences_set_updated_at
before update on public.notification_preferences
for each row execute function public.set_updated_at();

create trigger reminders_set_updated_at
before update on public.reminders
for each row execute function public.set_updated_at();
